### ISSUE TITLE
nuts segfault on device add/removal

### ISSUE THREAD

**Issue by stbuehler** [dosnut/nut#5]
<pre>
[New Thread 0x7ffff5048910 (LWP 21714)]
Device(wlan0) gotCarrier
ESSID: infeap
Set next environment 0
Interface_IPv4::start
Device(wlan0) lostCarrier
Interface_IPv4::stop
Device(wlan0) is down!
Device(wlan0) gotCarrier
ESSID: infeap
Set next environment 0
Interface_IPv4::start
Device(wlan0) is up!
Device(usb0) gotCarrier
Set next environment 0
Interface_IPv4::start
readARPPacket: recvfrom(...) failed: Network is down
Interface_IPv4::stop
Device(usb0) is down!
Couldn't get interface index of 'usb0'

Program received signal SIGSEGV, Segmentation fault.
QTextStreamPrivate::putString (this=0x64e980, s=..., number=false) at io/qtextstream.cpp:933
933     io/qtextstream.cpp: No such file or directory.
        in io/qtextstream.cpp
(gdb) quit
A debugging session is active.

        Inferior 1 [process 21711] will be killed.

Quit anyway? (y or n) n
Not confirmed.
(gdb) bt full
#0  QTextStreamPrivate::putString (this=0x64e980, s=..., number=false) at io/qtextstream.cpp:933
        tmp = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 1}, alloc = 0, size = 0, data = 0x64c0fa, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {
              _q_value = 6}, alloc = 0, size = 0, data = 0x7ffff75f9ada, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0x7c950, static codecForCStrings = 0x0}
        padSize = <value optimized out>
#1  0x00007ffff72af376 in QTextStream::operator<< (this=0x64c400, string=...) at io/qtextstream.cpp:2511
        d = 0x64e980
#2  0x000000000040cd54 in nuts::Device::lostCarrier (this=0x0) at device.cpp:259
No locals.
#3  0x0000000000415a62 in nuts::DeviceManager::ca_timer (this=0x678e60) at device.cpp:105
        e = {ifName = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 1}, alloc = 0, size = 0, data = 0x64c0fa, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {
              ref = {_q_value = 6}, alloc = 0, size = 0, data = 0x7ffff75f9ada, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0x68c430, static codecForCStrings = 0x0}, ifIndex = 0, up = false}
#4  0x000000000042be08 in nuts::DeviceManager::qt_metacall (this=0x678e60, _c=QMetaObject::InvokeMetaMethod, _id=6603776, _a=0x7fffffffe030) at build/moc_device.cpp:83
No locals.
#5  0x00007ffff7319df2 in QMetaObject::activate (sender=0x678ed8, from_signal_index=<value optimized out>, to_signal_index=4, argv=0x64c0e0) at kernel/qobject.cpp:3112
        previousSender = 0x0
        method = 6
        currentSender = {sender = 0x678ed8, signal = 4, ref = 1}
        count = 1
        signal = 4
        empty_argv = {0x0}
        locker = {{mtx = 0x64d788, val = 6608776}}
        currentThreadData = 0x64d730
        connectionLists = 0x682a00
#6  0x00007ffff7314353 in QObject::event (this=0x678ed8, e=0x78) at kernel/qobject.cpp:1074
No locals.
#7  0x00007ffff7304c9c in QCoreApplication::notifyInternal (this=0x7fffffffe5d0, receiver=0x678ed8, event=0x7fffffffe2f0) at kernel/qcoreapplication.cpp:610
        result = false
        cbdata = {0x678ed8, 0x7fffffffe2f0, 0x7fffffffe26f}
        threadData = 0x64d730
        returnValue = <value optimized out>
#8  0x00007ffff73312c6 in QCoreApplication::sendEvent (this=0x6671c0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:213
No locals.
#9  QTimerInfoList::activateTimers (this=0x6671c0) at kernel/qeventdispatcher_unix.cpp:580
        e = {<QEvent> = {_vptr.QEvent = 0x7ffff75f3610, d = 0x0, t = 1, posted = 0, spont = 0, m_accept = 1, reserved = 8191}, id = 3}
        firstTime = true
        currentTime = {tv_sec = 26340, tv_usec = 712957}
        n_act = 1
        saveFirstTimerInfo = 0x0
        saveCurrentTimerInfo = 0x0
#10 0x00007ffff732d658 in timerSourceDispatch (source=<value optimized out>) at kernel/qeventdispatcher_glib.cpp:184
        timerSource = <value optimized out>
#11 idleTimerSourceDispatch (source=<value optimized out>) at kernel/qeventdispatcher_glib.cpp:231
No locals.
#12 0x00007ffff59a412a in g_main_dispatch (context=0x666120) at /tmp/buildd/glib2.0-2.22.2/glib/gmain.c:1960
        __PRETTY_FUNCTION__ = "g_main_dispatch"
#13 IA__g_main_context_dispatch (context=0x666120) at /tmp/buildd/glib2.0-2.22.2/glib/gmain.c:2513
No locals.
#14 0x00007ffff59a7988 in g_main_context_iterate (context=0x666120, block=1, dispatch=1, self=<value optimized out>) at /tmp/buildd/glib2.0-2.22.2/glib/gmain.c:2591
        max_priority = 2147483647
        timeout = 332
        some_ready = 1
        nfds = 9
        allocated_nfds = <value optimized out>
        fds = 0x6cc8b0
        __PRETTY_FUNCTION__ = "g_main_context_iterate"
#15 0x00007ffff59a7b3c in IA__g_main_context_iteration (context=0x666120, may_block=1) at /tmp/buildd/glib2.0-2.22.2/glib/gmain.c:2654
        retval = <value optimized out>
#16 0x00007ffff732d39c in QEventDispatcherGlib::processEvents (this=0x663650, flags=<value optimized out>) at kernel/qeventdispatcher_glib.cpp:407
        d = 0x663670
        canWait = true
        result = <value optimized out>
#17 0x00007ffff7303562 in QEventLoop::processEvents (this=<value optimized out>, flags=...) at kernel/qeventloop.cpp:149
        d = 0x6ce700
#18 0x00007ffff7303934 in QEventLoop::exec (this=0x7fffffffe570, flags=...) at kernel/qeventloop.cpp:201
        d = 0x6ce700
        app = 0x7fffffffe5d0
#19 0x00007ffff7305ba4 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:888
        threadData = 0x64d730
        eventLoop = {<QObject> = {_vptr.QObject = 0x7ffff75f5670, static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff7399ac0 "QObject", data = 0x7ffff7399b60, extradata = 0x7ffff75ee700}}, d_ptr = 0x6ce700, static staticQtMetaObject = {d = {
                superdata = 0x0, stringdata = 0x7ffff73a3340 "Qt", data = 0x7ffff73a66c0, extradata = 0x0}}}, static staticMetaObject = {d = {superdata = 0x64c1a0, stringdata = 0x7ffff73ab7c0 "QEventLoop", data = 0x7ffff73ab7e0, extradata = 0x0}}}
        returnCode = -1
#20 0x000000000040b096 in mainApp (argc=1, argv=<value optimized out>) at main.cpp:30
        app = {<QObject> = {_vptr.QObject = 0x7ffff75f5730, static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff7399ac0 "QObject", data = 0x7ffff7399b60, extradata = 0x7ffff75ee700}}, d_ptr = 0x6625b0, static staticQtMetaObject = {d = {
                superdata = 0x0, stringdata = 0x7ffff73a3340 "Qt", data = 0x7ffff73a66c0, extradata = 0x0}}}, static staticMetaObject = {d = {superdata = 0x64c1a0, stringdata = 0x7ffff73ab860 "QCoreApplication", data = 0x7ffff73ab900, extradata = 0x0}},
          static self = 0x7fffffffe5d0}
        sighandler = <value optimized out>
        devManager = <value optimized out>
#21 0x000000000040b2b9 in main (argc=1, argv=0x7fffffffe728) at main.cpp:49
        res = <value optimized out>
</pre>

**Comment by stbuehler** [comment]
Was fixed in 7027ebf62f690a60e62d03657980ff2ad300a4c1
